stages:
  - deploy

trigger_deploy_bot:
  stage: deploy
  script:
    - ls -al
    - echo "$SSH_KEY_VARIABLE" > ssh_key.pem
    - chmod 400 ssh_key.pem 
    - ssh - i ssh_key.pem -o StrictHostKeyChecking=no $USERNAME@HOSTNAME "cd ./JobLinksOrganizer"; "./deploy.sh"